import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import MarqueeeText from "@/components/Marqueee";


const hindSiliguri = Hind_Siliguri({
  subsets: ["latin","bengali"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <MarqueeeText></MarqueeeText>
        <main>{children}</main>
        <div>footer</div>
      </body>
    </html>
  );
}
